
### main2.py
### 루트 조회
GET http://127.0.0.1:8000/

### 할 일 목록 조회
GET http://127.0.0.1:8000/todos

### 할 일 생성
POST http://127.0.0.1:8000/todos

### 할 일 수정
PUT http://127.0.0.1:8000/todos

### 할 일 삭제
DELETE http://127.0.0.1:8000/todos

#################################################################

### main3.py
### 루트 조회
GET http://127.0.0.1:8000/

### 할 일 목록 조회
GET http://127.0.0.1:8000/todos

### 할 일 단일 조회
GET http://127.0.0.1:8000/todos/1

### 존재하지 않는 id 조회
GET http://127.0.0.1:8000/todos/99

### 잘못된 타입의 id 조회
GET http://127.0.0.1:8000/todos/abc

### 할 일 생성
POST http://127.0.0.1:8000/todos
Content-Type: application/json

{
  "title": "우유 사기",
  "completed": false
}

### 할 일 수정
PUT http://127.0.0.1:8000/todos/2
Content-Type: application/json

{
  "title": "우유와 빵 사기",
  "completed": true
}

### 할 일 삭제
DELETE http://127.0.0.1:8000/todos/3


#################################################################

### main4.py
### completed 쿼리 파라미터 없음
GET http://127.0.0.1:8000/todos

### completed=true
GET http://127.0.0.1:8000/todos?completed=true

### completed=false
GET http://127.0.0.1:8000/todos?completed=false

### completed + title 조합
GET http://127.0.0.1:8000/todos/search?completed=true&title=우유

### 페이지네이션 기본값
GET http://127.0.0.1:8000/todos/page

### 페이지네이션 page+size
GET http://127.0.0.1:8000/todos/page?page=2&size=1      ### todos[1:2]

### keyword 필수 쿼리 파라미터 - 정상
GET http://127.0.0.1:8000/todos/keyword?keyword=우유

### keyword 없음 - 422 에러 발생
GET http://127.0.0.1:8000/todos/keyword

### tags 한 번 전달
GET http://127.0.0.1:8000/todos/tags?tags=긴급

### tags 여러 번 전달
GET http://127.0.0.1:8000/todos/tags?tags=긴급&tags=집안일


#################################################################


### main5.py
### 전달받은 항목으로 새로 추가
POST http://127.0.0.1:8000/todos
Content-Type: application/json

{
  "title": "우유 사기",
  "completed": false
}

### 할 일 수정
### {"id": 2, "title": "책 반납하기", "completed": True} 이 수정 대상
PUT http://127.0.0.1:8000/todos/2   ### 하나는 경로에 또 다른 하나는 body로 전달
Content-Type: application/json

{
  "title": "우유와 빵 사기",
  "completed": true
}


#################################################################


### main6.py
### 루트 조회
GET http://127.0.0.1:8000/

### 할 일 목록 조회
GET http://127.0.0.1:8000/todos

### completed=true
GET http://127.0.0.1:8000/todos?completed=true

### completed=false
GET http://127.0.0.1:8000/todos?completed=false

### 할 일 단일 조회
GET http://127.0.0.1:8000/todos/1

### 존재하지 않는 id 조회
GET http://127.0.0.1:8000/todos/99

### 잘못된 타입의 id 조회 - 422 에러
GET http://127.0.0.1:8000/todos/abc

### 할 일 생성 - 201 Created
POST http://127.0.0.1:8000/todos
Content-Type: application/json

{
  "title": "운동하기",
  "completed": false
}

### 할 일 수정
PUT http://127.0.0.1:8000/todos/2
Content-Type: application/json

{
  "title": "우유와 빵 사기",
  "completed": true
}

### 할 일 삭제 - 204 No Content
DELETE http://127.0.0.1:8000/todos/3